
# add this to ../makefile:
# exercises-[name]:
#     (cd exercises/[name] && make)

run: group_table_0.tex
	$(NOOP)

group_table_0.tex: group_table_0.py
	python group_table_0.py > group_table_0.tex

